version: "3"

services:
  tracking:
    container_name: "tracking-service"
    build: .
    image: yoksar/tracking-service
    environment:
      DATABASE_URL: jdbc:mysql://192.168.178.24:9040/projectdb
      DATABASE_USER: mysql
      DATABASE_PASS: mysql
    ports:
      - 9300:8080
    restart: unless-stopped