version: '3'

services:
  tracking:
    image: maven:alpine
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/default
      DATABASE_USER: mysql
      DATABASE_PASS: mysql
    volumes:
      - ./target:/app
    command: java -jar /app/trackingService-1.0.0.jar
    ports:
      - 9000:8080
  
  db:
    image: mysql:8.0.15
    volumes:
       - ./volumes/db/data/:/var/lib/mysql/ 
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: supersecret