kumuluzee:
  amqp:
    rabbitmq:
      hosts:
        - name: rabbitmq
          url: 192.168.178.24
          password: admin
          username: admin
          exchanges:
            - name: trackingExchange
              type: direct
  
  datasources:
    - jndi-name: jdbc/tracking
      connection-url: '${DATABASE_URL}'
      username: '${DATABASE_USER}'
      password: '${DATABASE_PASS}'
      pool:
        max-size: 20

    
